version: "3.8"
services: 
    redis:
        image: redis
        volumes: 
            - "fetch-volume:/data"
        networks: 
            - fetch-net
    transaction-manager:
        build:
            context: "."
            dockerfile: Dockerfile
        environment: 
            - MANAGER_TYPE=REDIS
            - REDIS_URI=redis
            - PORT=8080
        ports:
            - 8080:8080
        networks: 
            - fetch-net
        depends_on: redis
networks: 
    fetch-net:
volumes: 
    fetch-volume: