version: "3.8"
services: 
    transaction-manager:
        build:
            context: "."
            dockerfile: Dockerfile
        environment: 
            - MANAGER_TYPE=MEMORY
            - PORT=8080
        ports:
            - 8080:8080
        networks: 
            - fetch-net
networks: 
    fetch-net: